version: '3.9'
services:
  node:
    container_name: teste_backend
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    volumes:
     - .:/home/app/library
     - /home/app/library/node_modules
    expose:
    - 4000
    restart: always

  database:
    image: postgis/postgis:15-3.3-alpine
    container_name: teste_database
    restart: always
    ports:
      - 5432:5432
    environment:
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASSWORD}
     - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432