version: '2'
services:
  library:
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon --exec npm run dev
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    volumes:
     - .:/home/app/library
     - /home/app/library/node_modules
    expose:
    - 4000